package cryptowatchmodels

type Prices struct {
	Allowance Prices_sub1 `json:"allowance"`
	Result    Prices_sub2 `json:"result"`
}

type Prices_sub2 struct {
	Bitfinex_avtbtc                   float64 `json:"bitfinex:avtbtc"`
	Bitfinex_avteth                   float64 `json:"bitfinex:avteth"`
	Bitfinex_avtusd                   float64 `json:"bitfinex:avtusd"`
	Bitfinex_bccbtc                   float64 `json:"bitfinex:bccbtc"`
	Bitfinex_bccusd                   float64   `json:"bitfinex:bccusd"`
	Bitfinex_bchbtc                   float64 `json:"bitfinex:bchbtc"`
	Bitfinex_bcheth                   float64 `json:"bitfinex:bcheth"`
	Bitfinex_bchusd                   float64   `json:"bitfinex:bchusd"`
	Bitfinex_bcubtc                   float64 `json:"bitfinex:bcubtc"`
	Bitfinex_bcuusd                   float64 `json:"bitfinex:bcuusd"`
	Bitfinex_bt1btc                   float64 `json:"bitfinex:bt1btc"`
	Bitfinex_bt1usd                   float64   `json:"bitfinex:bt1usd"`
	Bitfinex_bt2btc                   float64 `json:"bitfinex:bt2btc"`
	Bitfinex_bt2usd                   float64 `json:"bitfinex:bt2usd"`
	Bitfinex_btceur                   float64   `json:"bitfinex:btceur"`
	Bitfinex_btcusd                   float64   `json:"bitfinex:btcusd"`
	Bitfinex_btgbtc                   float64 `json:"bitfinex:btgbtc"`
	Bitfinex_btgusd                   float64   `json:"bitfinex:btgusd"`
	Bitfinex_dashbtc                  float64 `json:"bitfinex:dashbtc"`
	Bitfinex_dashusd                  float64 `json:"bitfinex:dashusd"`
	Bitfinex_databtc                  float64   `json:"bitfinex:databtc"`
	Bitfinex_dataeth                  float64   `json:"bitfinex:dataeth"`
	Bitfinex_datausd                  float64   `json:"bitfinex:datausd"`
	Bitfinex_datbtc                   float64   `json:"bitfinex:datbtc"`
	Bitfinex_dateth                   float64 `json:"bitfinex:dateth"`
	Bitfinex_datusd                   float64 `json:"bitfinex:datusd"`
	Bitfinex_edobtc                   float64 `json:"bitfinex:edobtc"`
	Bitfinex_edoeth                   float64 `json:"bitfinex:edoeth"`
	Bitfinex_edousd                   float64 `json:"bitfinex:edousd"`
	Bitfinex_eosbtc                   float64 `json:"bitfinex:eosbtc"`
	Bitfinex_eoseth                   float64 `json:"bitfinex:eoseth"`
	Bitfinex_eosusd                   float64 `json:"bitfinex:eosusd"`
	Bitfinex_etcbtc                   float64 `json:"bitfinex:etcbtc"`
	Bitfinex_etcusd                   float64 `json:"bitfinex:etcusd"`
	Bitfinex_ethbtc                   float64 `json:"bitfinex:ethbtc"`
	Bitfinex_ethusd                   float64 `json:"bitfinex:ethusd"`
	Bitfinex_etpbtc                   float64 `json:"bitfinex:etpbtc"`
	Bitfinex_etpeth                   float64 `json:"bitfinex:etpeth"`
	Bitfinex_etpusd                   float64 `json:"bitfinex:etpusd"`
	Bitfinex_iotbtc                   float64 `json:"bitfinex:iotbtc"`
	Bitfinex_ioteth                   float64 `json:"bitfinex:ioteth"`
	Bitfinex_iotusd                   float64 `json:"bitfinex:iotusd"`
	Bitfinex_ltcbtc                   float64 `json:"bitfinex:ltcbtc"`
	Bitfinex_ltcusd                   float64 `json:"bitfinex:ltcusd"`
	Bitfinex_neobtc                   float64 `json:"bitfinex:neobtc"`
	Bitfinex_neoeth                   float64 `json:"bitfinex:neoeth"`
	Bitfinex_neousd                   float64 `json:"bitfinex:neousd"`
	Bitfinex_omgbtc                   float64 `json:"bitfinex:omgbtc"`
	Bitfinex_omgeth                   float64 `json:"bitfinex:omgeth"`
	Bitfinex_omgusd                   float64 `json:"bitfinex:omgusd"`
	Bitfinex_qtumbtc                  float64 `json:"bitfinex:qtumbtc"`
	Bitfinex_qtumeth                  float64 `json:"bitfinex:qtumeth"`
	Bitfinex_qtumusd                  float64 `json:"bitfinex:qtumusd"`
	Bitfinex_sanbtc                   float64 `json:"bitfinex:sanbtc"`
	Bitfinex_saneth                   float64 `json:"bitfinex:saneth"`
	Bitfinex_sanusd                   float64 `json:"bitfinex:sanusd"`
	Bitfinex_xmrbtc                   float64 `json:"bitfinex:xmrbtc"`
	Bitfinex_xmrusd                   float64 `json:"bitfinex:xmrusd"`
	Bitfinex_xrpbtc                   float64   `json:"bitfinex:xrpbtc"`
	Bitfinex_xrpusd                   float64 `json:"bitfinex:xrpusd"`
	Bitfinex_zecbtc                   float64 `json:"bitfinex:zecbtc"`
	Bitfinex_zecusd                   float64 `json:"bitfinex:zecusd"`
	Bitflyer_bchbtc                   float64 `json:"bitflyer:bchbtc"`
	Bitflyer_btcfxjpy                 float64   `json:"bitflyer:btcfxjpy"`
	Bitflyer_btcjpy                   float64   `json:"bitflyer:btcjpy"`
	Bitflyer_btcjpy_biweekly_futures  float64   `json:"bitflyer:btcjpy-biweekly-futures"`
	Bitflyer_btcjpy_weekly_futures    float64   `json:"bitflyer:btcjpy-weekly-futures"`
	Bitflyer_btcusd                   float64 `json:"bitflyer:btcusd"`
	Bitflyer_ethbtc                   float64 `json:"bitflyer:ethbtc"`
	Bithumb_bchkrw                    float64   `json:"bithumb:bchkrw"`
	Bithumb_btckrw                    float64   `json:"bithumb:btckrw"`
	Bithumb_btgkrw                    float64   `json:"bithumb:btgkrw"`
	Bithumb_dashkrw                   float64   `json:"bithumb:dashkrw"`
	Bithumb_etckrw                    float64   `json:"bithumb:etckrw"`
	Bithumb_ethkrw                    float64   `json:"bithumb:ethkrw"`
	Bithumb_ltckrw                    float64   `json:"bithumb:ltckrw"`
	Bithumb_qtumbtc                   float64   `json:"bithumb:qtumbtc"`
	Bithumb_qtumeth                   float64   `json:"bithumb:qtumeth"`
	Bithumb_qtumkrw                   float64   `json:"bithumb:qtumkrw"`
	Bithumb_xmrkrw                    float64   `json:"bithumb:xmrkrw"`
	Bithumb_xrpkrw                    float64   `json:"bithumb:xrpkrw"`
	Bithumb_zeckrw                    float64   `json:"bithumb:zeckrw"`
	Bitmex_bchbtc_monthly_futures     float64 `json:"bitmex:bchbtc-monthly-futures"`
	Bitmex_bchbtc_quarterly_futures   float64   `json:"bitmex:bchbtc-quarterly-futures"`
	Bitmex_btcjpy_monthly_futures     float64   `json:"bitmex:btcjpy-monthly-futures"`
	Bitmex_btcjpy_quarterly_futures   float64   `json:"bitmex:btcjpy-quarterly-futures"`
	Bitmex_btcusd_monthly_futures     float64   `json:"bitmex:btcusd-monthly-futures"`
	Bitmex_btcusd_perpetual_futures   float64   `json:"bitmex:btcusd-perpetual-futures"`
	Bitmex_btcusd_quarterly_futures   float64   `json:"bitmex:btcusd-quarterly-futures"`
	Bitmex_dashbtc_monthly_futures    float64 `json:"bitmex:dashbtc-monthly-futures"`
	Bitmex_dashbtc_quarterly_futures  float64 `json:"bitmex:dashbtc-quarterly-futures"`
	Bitmex_etcbtc_weekly_futures      float64 `json:"bitmex:etcbtc-weekly-futures"`
	Bitmex_ethbtc_monthly_futures     float64 `json:"bitmex:ethbtc-monthly-futures"`
	Bitmex_ethbtc_quarterly_futures   float64 `json:"bitmex:ethbtc-quarterly-futures"`
	Bitmex_ltcbtc_monthly_futures     float64 `json:"bitmex:ltcbtc-monthly-futures"`
	Bitmex_ltcbtc_quarterly_futures   float64 `json:"bitmex:ltcbtc-quarterly-futures"`
	Bitmex_xmrbtc_monthly_futures     float64 `json:"bitmex:xmrbtc-monthly-futures"`
	Bitmex_xmrbtc_quarterly_futures   float64 `json:"bitmex:xmrbtc-quarterly-futures"`
	Bitmex_xrpbtc_monthly_futures     float64   `json:"bitmex:xrpbtc-monthly-futures"`
	Bitmex_xrpbtc_quarterly_futures   float64   `json:"bitmex:xrpbtc-quarterly-futures"`
	Bitmex_xtzbtc_biquarterly_futures float64 `json:"bitmex:xtzbtc-biquarterly-futures"`
	Bitmex_xtzbtc_monthly_futures     float64 `json:"bitmex:xtzbtc-monthly-futures"`
	Bitmex_xtzbtc_quarterly_futures   float64   `json:"bitmex:xtzbtc-quarterly-futures"`
	Bitmex_zecbtc_monthly_futures     float64 `json:"bitmex:zecbtc-monthly-futures"`
	Bitmex_zecbtc_quarterly_futures   float64 `json:"bitmex:zecbtc-quarterly-futures"`
	Bitsquare_btcaud                  float64   `json:"bitsquare:btcaud"`
	Bitsquare_btceur                  float64 `json:"bitsquare:btceur"`
	Bitsquare_btcusd                  float64 `json:"bitsquare:btcusd"`
	Bitsquare_etcbtc                  float64   `json:"bitsquare:etcbtc"`
	Bitsquare_ethbtc                  float64   `json:"bitsquare:ethbtc"`
	Bitsquare_ltcbtc                  float64   `json:"bitsquare:ltcbtc"`
	Bitstamp_bchbtc                   float64 `json:"bitstamp:bchbtc"`
	Bitstamp_bcheur                   float64 `json:"bitstamp:bcheur"`
	Bitstamp_bchusd                   float64 `json:"bitstamp:bchusd"`
	Bitstamp_btceur                   float64 `json:"bitstamp:btceur"`
	Bitstamp_btcusd                   float64 `json:"bitstamp:btcusd"`
	Bitstamp_ethbtc                   float64 `json:"bitstamp:ethbtc"`
	Bitstamp_etheur                   float64 `json:"bitstamp:etheur"`
	Bitstamp_ethusd                   float64 `json:"bitstamp:ethusd"`
	Bitstamp_eurusd                   float64 `json:"bitstamp:eurusd"`
	Bitstamp_ltcbtc                   float64 `json:"bitstamp:ltcbtc"`
	Bitstamp_ltceur                   float64 `json:"bitstamp:ltceur"`
	Bitstamp_ltcusd                   float64   `json:"bitstamp:ltcusd"`
	Bitstamp_xrpbtc                   float64   `json:"bitstamp:xrpbtc"`
	Bitstamp_xrpeur                   float64 `json:"bitstamp:xrpeur"`
	Bitstamp_xrpusd                   float64 `json:"bitstamp:xrpusd"`
	Bittrex_batbtc                    float64   `json:"bittrex:batbtc"`
	Bittrex_bccbtc                    float64 `json:"bittrex:bccbtc"`
	Bittrex_bccusdt                   float64 `json:"bittrex:bccusdt"`
	Bittrex_blkbtc                    float64   `json:"bittrex:blkbtc"`
	Bittrex_btcusdt                   float64 `json:"bittrex:btcusdt"`
	Bittrex_dcrbtc                    float64 `json:"bittrex:dcrbtc"`
	Bittrex_edgbtc                    float64   `json:"bittrex:edgbtc"`
	Bittrex_etcbtc                    float64 `json:"bittrex:etcbtc"`
	Bittrex_etceth                    float64 `json:"bittrex:etceth"`
	Bittrex_etcusdt                   float64 `json:"bittrex:etcusdt"`
	Bittrex_ethbtc                    float64 `json:"bittrex:ethbtc"`
	Bittrex_ethusdt                   float64 `json:"bittrex:ethusdt"`
	Bittrex_neobtc                    float64 `json:"bittrex:neobtc"`
	Bittrex_neoeth                    float64 `json:"bittrex:neoeth"`
	Bittrex_neousdt                   float64 `json:"bittrex:neousdt"`
	Bittrex_omgbtc                    float64 `json:"bittrex:omgbtc"`
	Bittrex_omgeth                    float64 `json:"bittrex:omgeth"`
	Bittrex_qtumbtc                   float64 `json:"bittrex:qtumbtc"`
	Bittrex_stratbtc                  float64 `json:"bittrex:stratbtc"`
	Bittrex_vrcbtc                    float64   `json:"bittrex:vrcbtc"`
	Bittrex_vrmbtc                    float64 `json:"bittrex:vrmbtc"`
	Bittrex_vtcbtc                    float64 `json:"bittrex:vtcbtc"`
	Bittrex_xrpusdt                   float64 `json:"bittrex:xrpusdt"`
	Bittrex_zecusdt                   float64 `json:"bittrex:zecusdt"`
	Bittrex_zenbtc                    float64 `json:"bittrex:zenbtc"`
	Btce_bchbtc                       float64 `json:"btce:bchbtc"`
	Btce_bchusd                       float64   `json:"btce:bchusd"`
	Btce_btceur                       float64 `json:"btce:btceur"`
	Btce_btcrur                       float64   `json:"btce:btcrur"`
	Btce_btcusd                       float64   `json:"btce:btcusd"`
	Btce_ethbtc                       float64 `json:"btce:ethbtc"`
	Btce_etheur                       float64 `json:"btce:etheur"`
	Btce_ethltc                       float64 `json:"btce:ethltc"`
	Btce_ethrur                       float64 `json:"btce:ethrur"`
	Btce_ethusd                       float64 `json:"btce:ethusd"`
	Btce_ltcbtc                       float64 `json:"btce:ltcbtc"`
	Btce_ltcusd                       float64 `json:"btce:ltcusd"`
	Btce_nmcusd                       float64 `json:"btce:nmcusd"`
	Btce_ppcusd                       float64 `json:"btce:ppcusd"`
	Btce_zecbtc                       float64 `json:"btce:zecbtc"`
	Btce_zecusd                       float64 `json:"btce:zecusd"`
	Cexio_bchusd                      float64 `json:"cexio:bchusd"`
	Cexio_btceur                      float64 `json:"cexio:btceur"`
	Cexio_btcusd                      float64 `json:"cexio:btcusd"`
	Cexio_ethbtc                      float64 `json:"cexio:ethbtc"`
	Cexio_ethusd                      float64 `json:"cexio:ethusd"`
	Cexio_ltcbtc                      float64   `json:"cexio:ltcbtc"`
	Cexio_ltcusd                      float64   `json:"cexio:ltcusd"`
	Gdax_btceur                       float64   `json:"gdax:btceur"`
	Gdax_btcgbp                       float64 `json:"gdax:btcgbp"`
	Gdax_btcusd                       float64 `json:"gdax:btcusd"`
	Gdax_ethbtc                       float64 `json:"gdax:ethbtc"`
	Gdax_etheur                       float64 `json:"gdax:etheur"`
	Gdax_ethusd                       float64 `json:"gdax:ethusd"`
	Gdax_ltcbtc                       float64 `json:"gdax:ltcbtc"`
	Gdax_ltceur                       float64 `json:"gdax:ltceur"`
	Gdax_ltcusd                       float64 `json:"gdax:ltcusd"`
	Gemini_btcusd                     float64 `json:"gemini:btcusd"`
	Gemini_ethbtc                     float64 `json:"gemini:ethbtc"`
	Gemini_ethusd                     float64 `json:"gemini:ethusd"`
	Kraken_bchbtc                     float64 `json:"kraken:bchbtc"`
	Kraken_bcheur                     float64 `json:"kraken:bcheur"`
	Kraken_bchusd                     float64 `json:"kraken:bchusd"`
	Kraken_btccad                     float64   `json:"kraken:btccad"`
	Kraken_btceur                     float64 `json:"kraken:btceur"`
	Kraken_btcgbp                     float64   `json:"kraken:btcgbp"`
	Kraken_btcjpy                     float64   `json:"kraken:btcjpy"`
	Kraken_btcusd                     float64 `json:"kraken:btcusd"`
	Kraken_dashbtc                    float64 `json:"kraken:dashbtc"`
	Kraken_dasheur                    float64 `json:"kraken:dasheur"`
	Kraken_dashusd                    float64 `json:"kraken:dashusd"`
	Kraken_dogebtc                    float64   `json:"kraken:dogebtc"`
	Kraken_eosbtc                     float64 `json:"kraken:eosbtc"`
	Kraken_eoseth                     float64 `json:"kraken:eoseth"`
	Kraken_etcbtc                     float64 `json:"kraken:etcbtc"`
	Kraken_etceth                     float64 `json:"kraken:etceth"`
	Kraken_etceur                     float64 `json:"kraken:etceur"`
	Kraken_etcusd                     float64 `json:"kraken:etcusd"`
	Kraken_ethbtc                     float64 `json:"kraken:ethbtc"`
	Kraken_ethcad                     float64 `json:"kraken:ethcad"`
	Kraken_etheur                     float64 `json:"kraken:etheur"`
	Kraken_ethgbp                     float64   `json:"kraken:ethgbp"`
	Kraken_ethjpy                     float64   `json:"kraken:ethjpy"`
	Kraken_ethusd                     float64 `json:"kraken:ethusd"`
	Kraken_gnobtc                     float64 `json:"kraken:gnobtc"`
	Kraken_gnoeth                     float64 `json:"kraken:gnoeth"`
	Kraken_gnoeur                     float64   `json:"kraken:gnoeur"`
	Kraken_gnousd                     float64   `json:"kraken:gnousd"`
	Kraken_icnbtc                     float64   `json:"kraken:icnbtc"`
	Kraken_icneth                     float64 `json:"kraken:icneth"`
	Kraken_ltcbtc                     float64 `json:"kraken:ltcbtc"`
	Kraken_ltccad                     float64   `json:"kraken:ltccad"`
	Kraken_ltceur                     float64   `json:"kraken:ltceur"`
	Kraken_ltcusd                     float64 `json:"kraken:ltcusd"`
	Kraken_mlnbtc                     float64 `json:"kraken:mlnbtc"`
	Kraken_mlneth                     float64 `json:"kraken:mlneth"`
	Kraken_repbtc                     float64 `json:"kraken:repbtc"`
	Kraken_repcad                     float64   `json:"kraken:repcad"`
	Kraken_repeth                     float64 `json:"kraken:repeth"`
	Kraken_repeur                     float64 `json:"kraken:repeur"`
	Kraken_repjpy                     float64   `json:"kraken:repjpy"`
	Kraken_repusd                     float64   `json:"kraken:repusd"`
	Kraken_strbtc                     float64   `json:"kraken:strbtc"`
	Kraken_streur                     float64   `json:"kraken:streur"`
	Kraken_strusd                     float64   `json:"kraken:strusd"`
	Kraken_usdtusd                    float64 `json:"kraken:usdtusd"`
	Kraken_xmrbtc                     float64 `json:"kraken:xmrbtc"`
	Kraken_xmreur                     float64 `json:"kraken:xmreur"`
	Kraken_xmrusd                     float64 `json:"kraken:xmrusd"`
	Kraken_xrpbtc                     float64   `json:"kraken:xrpbtc"`
	Kraken_xrpcad                     float64   `json:"kraken:xrpcad"`
	Kraken_xrpeur                     float64 `json:"kraken:xrpeur"`
	Kraken_xrpjpy                     float64   `json:"kraken:xrpjpy"`
	Kraken_xrpusd                     float64 `json:"kraken:xrpusd"`
	Kraken_zecbtc                     float64 `json:"kraken:zecbtc"`
	Kraken_zeccad                     float64   `json:"kraken:zeccad"`
	Kraken_zeceur                     float64 `json:"kraken:zeceur"`
	Kraken_zecgbp                     float64   `json:"kraken:zecgbp"`
	Kraken_zecjpy                     float64   `json:"kraken:zecjpy"`
	Kraken_zecusd                     float64 `json:"kraken:zecusd"`
	Luno_btczar                       float64   `json:"luno:btczar"`
	Okcoin_btccny                     float64   `json:"okcoin:btccny"`
	Okcoin_btcusd                     float64 `json:"okcoin:btcusd"`
	Okcoin_btcusd_biweekly_futures    float64 `json:"okcoin:btcusd-biweekly-futures"`
	Okcoin_btcusd_quarterly_futures   float64   `json:"okcoin:btcusd-quarterly-futures"`
	Okcoin_btcusd_weekly_futures      float64   `json:"okcoin:btcusd-weekly-futures"`
	Okcoin_ltccny                     float64   `json:"okcoin:ltccny"`
	Okcoin_ltcusd                     float64   `json:"okcoin:ltcusd"`
	Okcoin_ltcusd_biweekly_futures    float64 `json:"okcoin:ltcusd-biweekly-futures"`
	Okcoin_ltcusd_quarterly_futures   float64 `json:"okcoin:ltcusd-quarterly-futures"`
	Okcoin_ltcusd_weekly_futures      float64 `json:"okcoin:ltcusd-weekly-futures"`
	Poloniex_ampbtc                   float64   `json:"poloniex:ampbtc"`
	Poloniex_ardrbtc                  float64   `json:"poloniex:ardrbtc"`
	Poloniex_bchbtc                   float64 `json:"poloniex:bchbtc"`
	Poloniex_bcheth                   float64 `json:"poloniex:bcheth"`
	Poloniex_bchusdt                  float64 `json:"poloniex:bchusdt"`
	Poloniex_bcnbtc                   float64   `json:"poloniex:bcnbtc"`
	Poloniex_bcnxmr                   float64   `json:"poloniex:bcnxmr"`
	Poloniex_bcybtc                   float64   `json:"poloniex:bcybtc"`
	Poloniex_belabtc                  float64   `json:"poloniex:belabtc"`
	Poloniex_blkbtc                   float64   `json:"poloniex:blkbtc"`
	Poloniex_blkxmr                   float64 `json:"poloniex:blkxmr"`
	Poloniex_btcdbtc                  float64 `json:"poloniex:btcdbtc"`
	Poloniex_btcdxmr                  float64 `json:"poloniex:btcdxmr"`
	Poloniex_btcusdt                  float64 `json:"poloniex:btcusdt"`
	Poloniex_btmbtc                   float64   `json:"poloniex:btmbtc"`
	Poloniex_btsbtc                   float64   `json:"poloniex:btsbtc"`
	Poloniex_burstbtc                 float64   `json:"poloniex:burstbtc"`
	Poloniex_clambtc                  float64 `json:"poloniex:clambtc"`
	Poloniex_cvcbtc                   float64   `json:"poloniex:cvcbtc"`
	Poloniex_cvceth                   float64 `json:"poloniex:cvceth"`
	Poloniex_daobtc                   float64   `json:"poloniex:daobtc"`
	Poloniex_daoeth                   float64   `json:"poloniex:daoeth"`
	Poloniex_dashbtc                  float64 `json:"poloniex:dashbtc"`
	Poloniex_dashusdt                 float64   `json:"poloniex:dashusdt"`
	Poloniex_dashxmr                  float64 `json:"poloniex:dashxmr"`
	Poloniex_dcrbtc                   float64 `json:"poloniex:dcrbtc"`
	Poloniex_dgbbtc                   float64   `json:"poloniex:dgbbtc"`
	Poloniex_dogebtc                  float64   `json:"poloniex:dogebtc"`
	Poloniex_emc2btc                  float64   `json:"poloniex:emc2btc"`
	Poloniex_etcbtc                   float64 `json:"poloniex:etcbtc"`
	Poloniex_etceth                   float64 `json:"poloniex:etceth"`
	Poloniex_etcusdt                  float64 `json:"poloniex:etcusdt"`
	Poloniex_ethbtc                   float64 `json:"poloniex:ethbtc"`
	Poloniex_ethusdt                  float64 `json:"poloniex:ethusdt"`
	Poloniex_expbtc                   float64 `json:"poloniex:expbtc"`
	Poloniex_fctbtc                   float64 `json:"poloniex:fctbtc"`
	Poloniex_fldcbtc                  float64   `json:"poloniex:fldcbtc"`
	Poloniex_flobtc                   float64   `json:"poloniex:flobtc"`
	Poloniex_gamebtc                  float64 `json:"poloniex:gamebtc"`
	Poloniex_gasbtc                   float64 `json:"poloniex:gasbtc"`
	Poloniex_gaseth                   float64 `json:"poloniex:gaseth"`
	Poloniex_gnobtc                   float64 `json:"poloniex:gnobtc"`
	Poloniex_gnoeth                   float64 `json:"poloniex:gnoeth"`
	Poloniex_gntbtc                   float64   `json:"poloniex:gntbtc"`
	Poloniex_gnteth                   float64 `json:"poloniex:gnteth"`
	Poloniex_grcbtc                   float64   `json:"poloniex:grcbtc"`
	Poloniex_hucbtc                   float64   `json:"poloniex:hucbtc"`
	Poloniex_lbcbtc                   float64   `json:"poloniex:lbcbtc"`
	Poloniex_lskbtc                   float64 `json:"poloniex:lskbtc"`
	Poloniex_lsketh                   float64 `json:"poloniex:lsketh"`
	Poloniex_ltcbtc                   float64 `json:"poloniex:ltcbtc"`
	Poloniex_ltcusdt                  float64 `json:"poloniex:ltcusdt"`
	Poloniex_ltcxmr                   float64 `json:"poloniex:ltcxmr"`
	Poloniex_maidbtc                  float64   `json:"poloniex:maidbtc"`
	Poloniex_maidxmr                  float64 `json:"poloniex:maidxmr"`
	Poloniex_nautbtc                  float64   `json:"poloniex:nautbtc"`
	Poloniex_navbtc                   float64 `json:"poloniex:navbtc"`
	Poloniex_neosbtc                  float64 `json:"poloniex:neosbtc"`
	Poloniex_nmcbtc                   float64 `json:"poloniex:nmcbtc"`
	Poloniex_notebtc                  float64   `json:"poloniex:notebtc"`
	Poloniex_nxcbtc                   float64   `json:"poloniex:nxcbtc"`
	Poloniex_nxtbtc                   float64   `json:"poloniex:nxtbtc"`
	Poloniex_nxtusdt                  float64 `json:"poloniex:nxtusdt"`
	Poloniex_nxtxmr                   float64 `json:"poloniex:nxtxmr"`
	Poloniex_omgbtc                   float64 `json:"poloniex:omgbtc"`
	Poloniex_omgeth                   float64 `json:"poloniex:omgeth"`
	Poloniex_omnibtc                  float64 `json:"poloniex:omnibtc"`
	Poloniex_pascbtc                  float64   `json:"poloniex:pascbtc"`
	Poloniex_pinkbtc                  float64   `json:"poloniex:pinkbtc"`
	Poloniex_potbtc                   float64   `json:"poloniex:potbtc"`
	Poloniex_ppcbtc                   float64 `json:"poloniex:ppcbtc"`
	Poloniex_radsbtc                  float64 `json:"poloniex:radsbtc"`
	Poloniex_repbtc                   float64 `json:"poloniex:repbtc"`
	Poloniex_repeth                   float64 `json:"poloniex:repeth"`
	Poloniex_repusdt                  float64 `json:"poloniex:repusdt"`
	Poloniex_ricbtc                   float64   `json:"poloniex:ricbtc"`
	Poloniex_sbdbtc                   float64 `json:"poloniex:sbdbtc"`
	Poloniex_scbtc                    float64   `json:"poloniex:scbtc"`
	Poloniex_sdcbtc                   float64   `json:"poloniex:sdcbtc"`
	Poloniex_sjcxbtc                  float64   `json:"poloniex:sjcxbtc"`
	Poloniex_steembtc                 float64   `json:"poloniex:steembtc"`
	Poloniex_steemeth                 float64 `json:"poloniex:steemeth"`
	Poloniex_storjbtc                 float64   `json:"poloniex:storjbtc"`
	Poloniex_stratbtc                 float64 `json:"poloniex:stratbtc"`
	Poloniex_strbtc                   float64   `json:"poloniex:strbtc"`
	Poloniex_strusdt                  float64 `json:"poloniex:strusdt"`
	Poloniex_sysbtc                   float64   `json:"poloniex:sysbtc"`
	Poloniex_viabtc                   float64 `json:"poloniex:viabtc"`
	Poloniex_vrcbtc                   float64   `json:"poloniex:vrcbtc"`
	Poloniex_vtcbtc                   float64 `json:"poloniex:vtcbtc"`
	Poloniex_xbcbtc                   float64 `json:"poloniex:xbcbtc"`
	Poloniex_xcpbtc                   float64 `json:"poloniex:xcpbtc"`
	Poloniex_xembtc                   float64   `json:"poloniex:xembtc"`
	Poloniex_xmrbtc                   float64 `json:"poloniex:xmrbtc"`
	Poloniex_xmrusdt                  float64 `json:"poloniex:xmrusdt"`
	Poloniex_xpmbtc                   float64   `json:"poloniex:xpmbtc"`
	Poloniex_xrpbtc                   float64   `json:"poloniex:xrpbtc"`
	Poloniex_xrpusdt                  float64 `json:"poloniex:xrpusdt"`
	Poloniex_xvcbtc                   float64   `json:"poloniex:xvcbtc"`
	Poloniex_zecbtc                   float64 `json:"poloniex:zecbtc"`
	Poloniex_zeceth                   float64 `json:"poloniex:zeceth"`
	Poloniex_zecusdt                  float64 `json:"poloniex:zecusdt"`
	Poloniex_zecxmr                   float64 `json:"poloniex:zecxmr"`
	Poloniex_zrxbtc                   float64   `json:"poloniex:zrxbtc"`
	Poloniex_zrxeth                   float64 `json:"poloniex:zrxeth"`
	Qryptos_etcbtc                    float64   `json:"qryptos:etcbtc"`
	Qryptos_ethbtc                    float64 `json:"qryptos:ethbtc"`
	Qryptos_ltcbtc                    float64 `json:"qryptos:ltcbtc"`
	Qryptos_repbtc                    float64   `json:"qryptos:repbtc"`
	Qryptos_xmrbtc                    float64   `json:"qryptos:xmrbtc"`
	Qryptos_xrpbtc                    float64   `json:"qryptos:xrpbtc"`
	Qryptos_zecbtc                    float64   `json:"qryptos:zecbtc"`
	Quoine_bchjpy                     float64 `json:"quoine:bchjpy"`
	Quoine_bchsgd                     float64 `json:"quoine:bchsgd"`
	Quoine_bchusd                     float64   `json:"quoine:bchusd"`
	Quoine_btcaud                     float64 `json:"quoine:btcaud"`
	Quoine_btccny                     float64   `json:"quoine:btccny"`
	Quoine_btceur                     float64 `json:"quoine:btceur"`
	Quoine_btchkd                     float64 `json:"quoine:btchkd"`
	Quoine_btcidr                     float64   `json:"quoine:btcidr"`
	Quoine_btcinr                     float64   `json:"quoine:btcinr"`
	Quoine_btcjpy                     float64   `json:"quoine:btcjpy"`
	Quoine_btcphp                     float64 `json:"quoine:btcphp"`
	Quoine_btcsgd                     float64 `json:"quoine:btcsgd"`
	Quoine_btcusd                     float64   `json:"quoine:btcusd"`
	Quoine_ethaud                     float64   `json:"quoine:ethaud"`
	Quoine_ethbtc                     float64 `json:"quoine:ethbtc"`
	Quoine_ethcny                     float64   `json:"quoine:ethcny"`
	Quoine_etheur                     float64   `json:"quoine:etheur"`
	Quoine_ethhkd                     float64   `json:"quoine:ethhkd"`
	Quoine_ethidr                     float64   `json:"quoine:ethidr"`
	Quoine_ethinr                     float64   `json:"quoine:ethinr"`
	Quoine_ethjpy                     float64 `json:"quoine:ethjpy"`
	Quoine_ethphp                     float64   `json:"quoine:ethphp"`
	Quoine_ethsgd                     float64 `json:"quoine:ethsgd"`
	Quoine_ethusd                     float64 `json:"quoine:ethusd"`
}

type Prices_sub1 struct {
	Cost      float64 `json:"cost"`
	Remaining float64 `json:"remaining"`
}
