// Code generated by "stringer -type=CurrencyType"; DO NOT EDIT.

package types

import "strconv"

const _CurrencyType_name = "ETHIOTLTCXMRXEMADANEONXTXLMXRP"

var _CurrencyType_index = [...]uint8{0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30}

func (i CurrencyType) String() string {
	if i < 0 || i >= CurrencyType(len(_CurrencyType_index)-1) {
		return "CurrencyType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CurrencyType_name[_CurrencyType_index[i]:_CurrencyType_index[i+1]]
}
