// Code generated by "stringer -type=MarketType"; DO NOT EDIT.

package types

import "strconv"

const _MarketType_name = "BitfinexBittrexPoloniex"

var _MarketType_index = [...]uint8{0, 8, 15, 23}

func (i MarketType) String() string {
	if i < 0 || i >= MarketType(len(_MarketType_index)-1) {
		return "MarketType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MarketType_name[_MarketType_index[i]:_MarketType_index[i+1]]
}
