// Code generated by "stringer -type=PairType"; DO NOT EDIT.

package types

import "strconv"

const _PairType_name = "EthbtcEthusdBtcusdIotbtcIotusdLtcbtcLtcusdXmrbtcXmrusdXembtcXemusdAdabtcAdausdNeobtcNeousdNxtbtcNxtusdXlmbtcXlmusdXrpbtcXrpusdXvgusdBchusd"

var _PairType_index = [...]uint8{0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96, 102, 108, 114, 120, 126, 132, 138}

func (i PairType) String() string {
	if i < 0 || i >= PairType(len(_PairType_index)-1) {
		return "PairType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PairType_name[_PairType_index[i]:_PairType_index[i+1]]
}
