// Code generated by "stringer -type=CurrencyType"; DO NOT EDIT.

package models

import "strconv"

const _CurrencyType_name = "ETHMIOTALTCXMRXEMADANEONXTXLMXRP"

var _CurrencyType_index = [...]uint8{0, 3, 8, 11, 14, 17, 20, 23, 26, 29, 32}

func (i CurrencyType) String() string {
	if i < 0 || i >= CurrencyType(len(_CurrencyType_index)-1) {
		return "CurrencyType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CurrencyType_name[_CurrencyType_index[i]:_CurrencyType_index[i+1]]
}
