// Code generated by "stringer -type=PairType"; DO NOT EDIT.

package models

import "strconv"

const _PairType_name = "EthbtcEthusdMiotabtcMiotausdLtcbtcLtcusdXmrbtcXmrusdXembtcXemusdAdabtcAdausdNeobtcNeousdNxtbtcNxtusdXlmbtcXlmusdXrpbtcXrpusd"

var _PairType_index = [...]uint8{0, 6, 12, 20, 28, 34, 40, 46, 52, 58, 64, 70, 76, 82, 88, 94, 100, 106, 112, 118, 124}

func (i PairType) String() string {
	if i < 0 || i >= PairType(len(_PairType_index)-1) {
		return "PairType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PairType_name[_PairType_index[i]:_PairType_index[i+1]]
}
